"""Installed skill entrypoint; repository locator generated by the installer."""
import json
import sys
from pathlib import Path

locator = Path(__file__).resolve().parents[1] / "repository.json"
try:
    ROOT = Path(json.loads(locator.read_text(encoding="utf-8"))["root"]).resolve()
    if not (ROOT / "hylms" / "runtime.py").is_file():
        raise ValueError()
except (OSError, ValueError, KeyError):
    print('{"status":"failed","code":"runtime_repository_missing"}')
    raise SystemExit(1)
sys.path.insert(0, str(ROOT))
from hylms.runtime import main
if __name__ == "__main__":
    if hasattr(sys.stdout, "reconfigure"):
        sys.stdout.reconfigure(encoding="utf-8")
    raise SystemExit(main())
