"""Public compatibility surface for the Hanyang LMS snapshot CLI."""

from .app import Application, main
from .assessments import (
    elapsed_seconds,
    normalize_classic_quiz_settings,
    normalize_new_quiz_settings,
    quiz_score_state,
    safe_quiz_lock_reason,
)
from .collector import CanvasCollector
from .content import (
    clean_block_text,
    clean_html,
    clean_inline_text,
    dedupe_dicts,
    normalize_attachment,
    normalize_rubric,
    normalize_rules,
    normalize_submission,
    sanitize_filename_component,
    sanitize_url,
)
from .core import (
    CANVAS_ORIGIN,
    CREDENTIAL_TARGET,
    DOCUMENT_EXTENSIONS,
    KST,
    SCHEMA_VERSION,
    SOURCE_NOT_COLLECTED,
    CanvasHTTPError,
    CanvasTransportError,
    CredentialStoreError,
    HylmsError,
    TermSelection,
    TermSelectionError,
    expected_term,
    extract_token_id,
    kst_iso,
    now_kst,
    parse_iso_datetime,
    select_current_term,
    source_status,
    stable_error_code,
    term_id_from_name,
    unwrap_collection,
)
from .credentials import CredentialRecord, WindowsCredentialStore
from .documents import DocumentDownloader
from .diff import (
    DECISION_SCHEMA_VERSION,
    MANUAL_SCHEMA_VERSION,
    STATE_SCHEMA_VERSION,
    commit_manual_state,
    commit_qa_pending_state,
    commit_state,
    discover_runs,
    migrate_state_v3_to_v4,
    migrate_state_v4_to_v5,
    next_run_diff,
    prepare_decision_packet,
    prepare_manual_packet,
    preview_manual_transaction,
    preview_state_transaction,
    record_failure,
    validate_state,
    validate_state_references,
)
from .http import (
    CanvasClient,
    HttpResponse,
    UrllibTransport,
    canonical_origin,
    parse_next_link,
    retry_after_seconds,
    safe_request_path,
)
from .learningx import LearningXBootstrap, LearningXCollector, LearningXHTTPError, LearningXSession
from .participation import (
    APPROVED_OWN_REPLY_RULES,
    PARTICIPATION_SCHEMA_VERSION,
    SUPPORTED_DISCUSSION_SNAPSHOT_SCHEMAS,
    EXAMPLE_OWN_REPLY_RULE_ID,
    discussion_participation_report,
    normalize_discussion_participation,
    validate_discussion_participation,
)
from .qa import (
    QA_SCHEMA_VERSION,
    build_qa_prompt,
    manual_qa_outcome,
    prepare_qa_packet,
    qa_next_action,
    validate_qa_verdict,
)
from .schedule import evaluate_summary, normalize_discussion_schedule, normalize_schedule
from .storage import (
    SnapshotRunner,
    atomic_write_json,
    course_stem,
    document_summary,
    document_summary_text,
    finalize_document_paths,
    find_previous_course,
    preserve_document_paths,
    read_previous_schema_version,
    read_previous_success,
    validate_snapshot,
)

__all__ = [
    "CALENDAR_SCHEMA_VERSION",
    "prepare_calendar",
    "render_ics",
    "write_ics",
    "GOOGLE_SYNC_SCHEMA_VERSION",
    "prepare_google_sync",
    "sync_google_calendar",
    "Application",
    "APPROVED_OWN_REPLY_RULES",
    "CANVAS_ORIGIN",
    "CREDENTIAL_TARGET",
    "CanvasClient",
    "CanvasCollector",
    "CanvasHTTPError",
    "CanvasTransportError",
    "CredentialRecord",
    "CredentialStoreError",
    "DECISION_SCHEMA_VERSION",
    "DOCUMENT_EXTENSIONS",
    "DocumentDownloader",
    "HylmsError",
    "HttpResponse",
    "KST",
    "LearningXBootstrap",
    "LearningXCollector",
    "LearningXHTTPError",
    "LearningXSession",
    "MANUAL_SCHEMA_VERSION",
    "NTFY_MESSAGE_LIMIT",
    "NTFY_SCHEMA_VERSION",
    "NTFY_SEPARATOR",
    "NTFY_TOPIC",
    "NTFY_URL",
    "PARTICIPATION_SCHEMA_VERSION",
    "QA_SCHEMA_VERSION",
    "SCHEMA_VERSION",
    "SOURCE_NOT_COLLECTED",
    "STATE_SCHEMA_VERSION",
    "SUPPORTED_DISCUSSION_SNAPSHOT_SCHEMAS",
    "SnapshotRunner",
    "TermSelection",
    "TermSelectionError",
    "EXAMPLE_OWN_REPLY_RULE_ID",
    "UrllibTransport",
    "UrllibNtfyTransport",
    "WindowsCredentialStore",
    "atomic_write_json",
    "acceptance_delivery",
    "build_qa_prompt",
    "canonical_origin",
    "clean_block_text",
    "clean_html",
    "clean_inline_text",
    "commit_manual_state",
    "commit_qa_pending_state",
    "commit_state",
    "course_stem",
    "document_summary",
    "document_summary_text",
    "discussion_participation_report",
    "discover_runs",
    "dedupe_dicts",
    "elapsed_seconds",
    "evaluate_summary",
    "expected_term",
    "extract_token_id",
    "finalize_document_paths",
    "find_previous_course",
    "kst_iso",
    "main",
    "manual_qa_outcome",
    "migrate_state_v3_to_v4",
    "migrate_state_v4_to_v5",
    "normalize_attachment",
    "normalize_classic_quiz_settings",
    "normalize_discussion_schedule",
    "normalize_discussion_participation",
    "normalize_new_quiz_settings",
    "normalize_rubric",
    "normalize_rules",
    "normalize_schedule",
    "normalize_submission",
    "next_run_diff",
    "now_kst",
    "parse_iso_datetime",
    "parse_next_link",
    "prepare_decision_packet",
    "prepare_manual_packet",
    "prepare_ntfy_delivery",
    "prepare_qa_packet",
    "preview_manual_transaction",
    "preview_state_transaction",
    "preserve_document_paths",
    "quiz_score_state",
    "qa_next_action",
    "read_previous_schema_version",
    "read_previous_success",
    "record_failure",
    "retry_after_seconds",
    "safe_quiz_lock_reason",
    "sanitize_filename_component",
    "sanitize_url",
    "send_ntfy_delivery",
    "safe_request_path",
    "select_current_term",
    "source_status",
    "stable_error_code",
    "term_id_from_name",
    "unwrap_collection",
    "validate_snapshot",
    "validate_discussion_participation",
    "validate_qa_verdict",
    "validate_state",
    "validate_state_references",
]

_NTFY_EXPORTS = {
    "NTFY_MESSAGE_LIMIT",
    "NTFY_SCHEMA_VERSION",
    "NTFY_SEPARATOR",
    "NTFY_TOPIC",
    "NTFY_URL",
    "UrllibNtfyTransport",
    "acceptance_delivery",
    "prepare_ntfy_delivery",
    "send_ntfy_delivery",
}


_CALENDAR_EXPORTS = {"CALENDAR_SCHEMA_VERSION", "prepare_calendar", "render_ics", "write_ics"}
_GOOGLE_EXPORTS = {"GOOGLE_SYNC_SCHEMA_VERSION", "prepare_google_sync", "sync_google_calendar"}


def __getattr__(name: str):
    if name not in _NTFY_EXPORTS | _CALENDAR_EXPORTS | _GOOGLE_EXPORTS:
        raise AttributeError(name)
    import importlib

    module_name = ".google_calendar" if name in _GOOGLE_EXPORTS else ".ics" if name in _CALENDAR_EXPORTS else ".ntfy"
    module = importlib.import_module(module_name, __name__)
    value = getattr(module, name)
    globals()[name] = value
    return value
